### ISSUE TITLE
data in client.ts should be language agnostic

### ISSUE THREAD

**Issue by ligi** [slockit/in3#22]
currently this tightly couples to typescript. I want to use it e.g. for native android - using ts would be a mistake there. So it would be great if the data defined in client.ts could live e.g. in a json - ideally in a separate repository.

**Comment by simon-jentzsch** [comment]
I'm not sure, if I understand you correctly, since I'm not sure what you mean with `data`? 
this client compiles typescript to simple javascript. So during runtime all data are just json-objects. 
SO as long as you are running javascript, this should work fine.
If you want to run it on native android, there will be the option to also use the c-version, which will publish very soon. This implementation is written completly in c and should also compile to a native library useable in android (and will be much faster ;-) and smaller ).

**Comment by ligi** [comment]
nice! 
I see b8f67ae7290648f0c52cc78579c4ef9abfc9cac6 is basically already doing what I wanted  - moving the server configuration from typescript to json - so closing this issue.
Perhaps this json could even live outside this repository so it can be shared between different implementations easily (ts, c, kotlin)
