### ISSUE TITLE
Error while running examples

### ISSUE THREAD

**Issue by radsal** [slockit/in3#57]
I tried to run the script `run.sh` within examples folder.

Got the following error:

<img width="838" alt="runsh_error" src="https://user-images.githubusercontent.com/6400446/86620015-3cf94900-bfd9-11ea-9c2b-65786bd23a5d.png">

While running this gist: https://gist.github.com/simon-jentzsch/48fd7a5e9fd59e6d3a0c00815d37d24d

Got following: 

<img width="841" alt="in3Contract_Error" src="https://user-images.githubusercontent.com/6400446/86620414-e9d3c600-bfd9-11ea-80ac-c57dbd54d528.png">

I am not sure what I am doing wrong and could not find a reference for expected output/logs.

**Comment by simon-jentzsch** [comment]
Hi thanks for the feedback. 
Since we are currently preparing to replace this typescript-implementation by a pure wasm-impl, I would suggest to use `in3-wasm` instead. We API is (almost) the same, so your code should work with the wasm-version as well.

See 
https://in3.readthedocs.io/en/develop/api-wasm.html#use-web3

The `in3-wasm`-version has the advantage that it adds only a small footprint and zero dependencies and runs with almost native speed. So please let me know if it works for you.

**Comment by radsal** [comment]
@simon-jentzsch `in3-wasm` works for me. Thanks.
